name: Test Examples

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every night at midnight UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  test-examples:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run examples
        run: |
          python examples/expressions.py
